name: Run Cucumber Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Grant execute permissions
      run: chmod +x ./node_modules/.bin/cucumber-js
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Cucumber tests
      run: ./node_modules/.bin/cucumber-js
      env:
        CHROME_BIN: /usr/bin/google-chrome
